version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *defaults
    steps:
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - run: npm run test
  analyze:
    <<: *defaults
    steps:
      - run: npm audit

workflows:
  full_checks:
    jobs:
      - build
      - test:
          requires: [build]
      #- analyze:
          #requires: [test]
