version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: echo "Working dir"
      - run: pwd
      - run: ls
      - run: npm i
      - run: ls
      #- save_cache:
      #    key: "npm-packages"
      #    path: /src/node_modules
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run: npm run test
  analyze:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run: npm audit

workflows:
  full_checks:
    jobs:
      - build
      - test:
          requires: [build]
      #- analyze:
          #requires: [test]
